### DISCUSSION TITLE
Header and Logo

### DISCUSSION THREAD

**Discussion by Dekker500** [hbstack/.github#10] [Issues and bugs]
Perhaps there is something missing in the documentation, or I am just missing something.

The Header module (https://hb.hugomods.com/en/docs/modules/header/overview/) gives the following configuration:
```
params:
  hb:
    header:
      brand: ""
      full_width: true
      sticky: true
      theme: ""
```
However I think it is missing the logo/image (https://github.com/hbstack/header/blob/main/layouts/partials/hb/modules/header/logo.html). Where should that be defined??
