### DISCUSSION TITLE
No uploaded artifact was found!

### DISCUSSION THREAD

**Discussion by sandsoncosta** [hbstack/.github#100] [Q&A] [answered]
Hello, Razon Yang. Can you help me this?

Run actions/deploy-pages@v2
Artifact exchange URL: https://pipelinesghubeus24.actions.githubusercontent.com/0yKsVc08ViQkH75ZhQ8NmwrAxGiEwNod4QycpqNYwoGplXkp[9](https://github.com/sandsoncosta/sandsoncosta.github.io/actions/runs/13204181916/job/36863404205#step:2:10)D/_apis/pipelines/workflows/13204181916/artifacts?api-version=6.0-preview
Error: Error: No uploaded artifact was found! Please check if there are any errors at build step, or uploaded artifact name is correct.
    at getSignedArtifactMetadata (/home/runner/work/_actions/actions/deploy-pages/v2/src/internal/api-client.js:94:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v2/src/internal/deployment.js:68:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v2/src/index.js:30:1)
Error: Error: No uploaded artifact was found! Please check if there are any errors at build step, or uploaded artifact name is correct.

**Comment by sandsoncosta** [comment]
```

      - name: Upload artifact
        # uses: actions/upload-pages-artifact@v1
        # uses: actions/upload-artifact@v4
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
```
