### DISCUSSION TITLE
toc-scrollspy not working

### DISCUSSION THREAD

**Discussion by evandde** [hbstack/.github#14] [Q&A] [answered]
What I did:

in hugo.yaml,
```
module:
  imports:
    ...
    - path: github.com/hbstack/blog/modules/toc-scrollspy
    - path: github.com/hbstack/docs/modules/toc-scrollspy
```

in shell (PowerShell)
```
hugo mod clean
hugo mod get -u ./...
hugo mod npm pack
npm update
```

But no changes in my toc. (e.g.: https://ffxiv.mew.kr/doc_g4install/chap1_basic/p5_optional/#win32-opengl-windows)

Please help me.
