### DISCUSSION TITLE
How can I apply ko.toml?

### DISCUSSION THREAD

**Discussion by evandde** [hbstack/.github#15] [Q&A] [answered]
Even though I set all of below
1. `defaultContentLanguage: ko` in hugo.yaml
2. in lanuages.yaml
 ```
ko:
  languageName: Korean
  weight: 1
```
3. `hugo mod get -u ./...`
there is no change regarding i18n things.
And also search window is not openning.

What do I need to do?

**Comment by razonyang** [comment]
Sorry, I didn't notice that you've executed `hugo mod get -u ./...`, could you please provide the output of `hugo mod graph`?
Sometime `hugo mod get -u ./...` doesn't work very well.

> And also search window is not openning.

Is there any error on browser console (`F12` on Chrome)?

**Reply by evandde** [reply]
I did `hugo mod tidy`, `hugo mod clean` and then `hugo mod get -u ./...` once again.

Here are the output of `hugo mod graph` after that.

```
github.com/evandde/evanote github.com/hbstack/gallery@v0.5.0
github.com/hbstack/gallery@v0.5.0 github.com/hbstack/hb@v0.5.0
github.com/hbstack/hb@v0.5.0 github.com/hugomods/hugopress@v0.1.0
github.com/hbstack/hb@v0.5.0 github.com/hugomods/base@v0.1.0
github.com/hbstack/hb@v0.5.0 github.com/gohugoio/hugo-mod-bootstrap-scss/v5@v5.20300.20002
github.com/gohugoio/hugo-mod-bootstrap-scss/v5@v5.20300.20002 github.com/twbs/bootstrap@v5.3.0-alpha3+incompatible
github.com/gohugoio/hugo-mod-bootstrap-scss/v5@v5.20300.20002 github.com/gohugoio/hugo-mod-jslibs-dist/popperjs/v2@v2.21100.20000
github.com/hbstack/gallery@v0.5.0 github.com/hbstack/bigger-picture@v0.9.2
github.com/hbstack/bigger-picture@v0.9.2 github.com/hugomods/icons/vendors/bootstrap@v0.5.0
github.com/hugomods/icons/vendors/bootstrap@v0.5.0 github.com/hugomods/icons@v0.6.0
github.com/hugomods/icons/vendors/bootstrap@v0.5.0 github.com/twbs/icons@v1.10.5
github.com/hbstack/bigger-picture@v0.9.2 github.com/henrygd/bigger-picture@v1.1.8
github.com/hbstack/gallery@v0.5.0 github.com/hbstack/bs-tooltip@v0.1.1
github.com/evandde/evanote github.com/hbstack/gallery/modules/breadcrumb@v0.1.0
github.com/hbstack/gallery/modules/breadcrumb@v0.1.0 github.com/hbstack/breadcrumb@v0.1.1
github.com/evandde/evanote github.com/hugomods/icons/vendors/font-awesome@v0.6.0
github.com/hugomods/icons/vendors/font-awesome@v0.6.0 github.com/hugomods/font-awesome@v6.4.0+incompatible
github.com/evandde/evanote github.com/hbstack/blog/modules/giscus@v0.1.3
github.com/hbstack/blog/modules/giscus@v0.1.3 github.com/hbstack/giscus@v0.1.0
github.com/hbstack/giscus@v0.1.0 github.com/hugomods/giscus@v0.1.0
github.com/hbstack/blog/modules/giscus@v0.1.3 github.com/hbstack/blog@v0.10.0
github.com/hbstack/blog@v0.10.0 github.com/hbstack/base@v0.1.5
github.com/hbstack/base@v0.1.5 github.com/hugomods/seo/modules/base@v0.1.0
github.com/hbstack/base@v0.1.5 github.com/hbstack/header@v0.1.15
github.com/hbstack/base@v0.1.5 github.com/hbstack/footer@v0.2.1
github.com/hbstack/blog@v0.10.0 github.com/hbstack/carousel@v0.2.1
github.com/hbstack/blog@v0.10.0 github.com/hbstack/socials@v0.1.3
github.com/hbstack/socials@v0.1.3 github.com/hugomods/icons/vendors/simple-icons@v0.11.0
github.com/hugomods/icons/vendors/simple-icons@v0.11.0 github.com/hugomods/simple-icons@v8.12.0+incompatible
github.com/hbstack/blog@v0.10.0 github.com/hugomods/gravatar@v0.2.0
github.com/hbstack/blog@v0.10.0 github.com/hugomods/images@v0.5.1
github.com/evandde/evanote github.com/hbstack/blog/modules/content-panel@v0.1.0
github.com/hbstack/blog/modules/content-panel@v0.1.0 github.com/hbstack/content-panel@v0.1.0
github.com/evandde/evanote github.com/hbstack/blog/modules/toc-scrollspy@v0.1.0
github.com/hbstack/blog/modules/toc-scrollspy@v0.1.0 github.com/hbstack/toc-scrollspy@v0.1.0
github.com/evandde/evanote github.com/hbstack/docs/modules/giscus@v0.1.3
github.com/hbstack/docs/modules/giscus@v0.1.3 github.com/hbstack/docs@v0.4.0
github.com/evandde/evanote github.com/hbstack/docs/modules/content-panel@v0.1.0
github.com/evandde/evanote github.com/hbstack/docs/modules/toc-scrollspy@v0.1.0
github.com/evandde/evanote github.com/hugomods/google-analytics@v0.1.0
github.com/evandde/evanote github.com/hugomods/google-adsense@v0.1.0
github.com/evandde/evanote github.com/hbstack/meta/recommended@v0.2.0
github.com/hbstack/meta/recommended@v0.2.0 github.com/hbstack/back-to-top@v0.1.2
github.com/hbstack/meta/recommended@v0.2.0 github.com/hbstack/code-block-panel@v0.1.1
github.com/hbstack/code-block-panel@v0.1.1 github.com/hbstack/snackbar@v0.1.0
github.com/hbstack/snackbar@v0.1.0 github.com/hugomods/snackbar@v0.1.1
github.com/hbstack/code-block-panel@v0.1.1 github.com/hugomods/code-block-panel@v0.1.1
github.com/hugomods/code-block-panel@v0.1.1 github.com/hugomods/i18n-js@v0.1.0
github.com/hbstack/meta/recommended@v0.2.0 github.com/hbstack/meta/docs@v0.1.0
github.com/hbstack/meta/docs@v0.1.0 github.com/hbstack/docs/modules/breadcrumb@v0.1.2
github.com/hbstack/meta/docs@v0.1.0 github.com/hbstack/docs/modules/featured-image@v0.2.0
github.com/hbstack/docs/modules/featured-image@v0.2.0 github.com/hbstack/blog/modules/featured-image@v0.2.0
github.com/hbstack/meta/docs@v0.1.0 github.com/hbstack/docs/modules/heading-sign@v0.1.2
github.com/hbstack/docs/modules/heading-sign@v0.1.2 github.com/hbstack/heading-sign@v0.1.3
github.com/hbstack/meta/docs@v0.1.0 github.com/hbstack/docs/modules/doc-nav@v0.2.1
github.com/hbstack/meta/recommended@v0.2.0 github.com/hbstack/meta/standard@v0.2.0
github.com/hbstack/meta/standard@v0.2.0 github.com/hbstack/meta/blog@v0.2.0
github.com/hbstack/meta/blog@v0.2.0 github.com/hbstack/blog/modules/breadcrumb@v0.1.2
github.com/hbstack/meta/blog@v0.2.0 github.com/hbstack/blog/modules/heading-sign@v0.1.3
github.com/hbstack/meta/blog@v0.2.0 github.com/hbstack/blog/modules/post-nav@v0.2.0
github.com/hbstack/meta/blog@v0.2.0 github.com/hbstack/blog/modules/related-posts@v0.1.2
github.com/hbstack/blog/modules/related-posts@v0.1.2 github.com/hbstack/slide@v0.1.0
github.com/hbstack/meta/standard@v0.2.0 github.com/hbstack/meta/content@v0.4.1
github.com/hbstack/meta/content@v0.4.1 github.com/hbstack/mermaid@v0.1.0
github.com/hbstack/mermaid@v0.1.0 github.com/hugomods/mermaid@v0.1.1
github.com/hbstack/meta/content@v0.4.1 github.com/hugomods/katex@v0.1.5
github.com/hugomods/katex@v0.1.5 github.com/KaTex/KaTex@v0.16.7
github.com/hbstack/meta/content@v0.4.1 github.com/hbstack/bootstrap@v0.1.2
github.com/hbstack/bootstrap@v0.1.2 github.com/hugomods/bootstrap@v0.6.1
github.com/hbstack/meta/content@v0.4.1 github.com/hugomods/shortcodes@v0.7.0
github.com/hbstack/meta/standard@v0.2.0 github.com/hbstack/meta/footer@v0.2.0
github.com/hbstack/meta/footer@v0.2.0 github.com/hbstack/footer/modules/socials@v0.1.4
github.com/hbstack/meta/standard@v0.2.0 github.com/hbstack/meta/header@v0.2.0
github.com/hbstack/meta/header@v0.2.0 github.com/hbstack/header/modules/language-picker@v0.1.2
github.com/hbstack/meta/header@v0.2.0 github.com/hbstack/header/modules/socials@v0.1.2
github.com/hbstack/meta/header@v0.2.0 github.com/hbstack/header/modules/search@v0.1.10
github.com/hbstack/header/modules/search@v0.1.10 github.com/hbstack/search@v0.1.7
github.com/hbstack/search@v0.1.7 github.com/hugomods/search@v0.1.2
github.com/hugomods/search@v0.1.2 github.com/hugomods/fuse-js@v0.1.0
github.com/hugomods/fuse-js@v0.1.0 github.com/krisk/Fuse@v6.6.2+incompatible
github.com/hbstack/meta/header@v0.2.0 github.com/hbstack/header/modules/theme-toggle@v0.1.2
github.com/hbstack/meta/standard@v0.2.0 github.com/hbstack/meta/seo@v0.2.0
github.com/hbstack/meta/seo@v0.2.0 github.com/hugomods/seo/modules/alternatives@v0.1.0
github.com/hbstack/meta/seo@v0.2.0 github.com/hugomods/seo/modules/favicons@v0.2.0
github.com/hbstack/meta/seo@v0.2.0 github.com/hugomods/seo/modules/open-graph@v0.1.0
github.com/hbstack/meta/seo@v0.2.0 github.com/hugomods/seo/modules/schema@v0.1.1
github.com/hbstack/meta/seo@v0.2.0 github.com/hugomods/seo/modules/translations@v0.1.0
github.com/hbstack/meta/seo@v0.2.0 github.com/hugomods/seo/modules/twitter-cards@v0.1.0
github.com/hbstack/meta/standard@v0.2.0 github.com/hbstack/syntax-highlighting/styles/gruvbox@v0.1.0
github.com/hbstack/syntax-highlighting/styles/gruvbox@v0.1.0 github.com/hbstack/syntax-highlighting@v0.1.0
github.com/hbstack/meta/recommended@v0.2.0 github.com/hbstack/noscript@v0.1.0
github.com/hbstack/meta/recommended@v0.2.0 github.com/hbstack/progress-bar@v0.1.0
github.com/hbstack/meta/recommended@v0.2.0 github.com/hbstack/pwa@v0.1.2
github.com/hbstack/pwa@v0.1.2 github.com/hugomods/pwa@v0.2.1
github.com/hugomods/pwa@v0.2.1 github.com/hugomods/workbox@v0.1.0
github.com/hugomods/workbox@v0.1.0 github.com/hugomods/idb-js@v0.1.0
github.com/hugomods/idb-js@v0.1.0 github.com/jakearchibald/idb@v7.1.1+incompatible
github.com/hugomods/workbox@v0.1.0 github.com/GoogleChrome/workbox@v6.5.4+incompatible
github.com/hbstack/meta/recommended@v0.2.0 github.com/hbstack/scrollbar@v0.1.0
```

FYI, this is mo module in hugo.yaml file

``` yaml
module:
  # For some regions can not access the proxy.golang.org, i.e. China.
  # See https://hugomods.com/en/blog/2023/04/go-and-hugo-proxy-servers/ for all available proxy servers.
  # proxy: https://goproxy.cn,direct

  # The order of module is very important, precedence from top to bottom.
  imports:
    - path: github.com/hbstack/gallery
    - path: github.com/hbstack/gallery/modules/breadcrumb

    # syntax highlighting, see https://hb.hugomods.com/en/docs/modules/syntax-highlighting/.
    # - path: github.com/hbstack/syntax-highlighting/styles/github-dark
  
    # icons modules
    - path: github.com/hugomods/icons/vendors/font-awesome
    # - path: github.com/hugomods/icons/vendors/mdi
    # - path: github.com/hugomods/icons/vendors/simple-icons
    # - path: github.com/hugomods/icons/vendors/tabler
    # - path: github.com/hugomods/icons/vendors/feather

    # blog comments engine
    - path: github.com/hbstack/blog/modules/giscus
    # - path: github.com/hbstack/blog/modules/disqus
    # - path: github.com/hbstack/blog/modules/utterances

    # blog modules
    - path: github.com/hbstack/blog/modules/content-panel
    - path: github.com/hbstack/blog/modules/toc-scrollspy

    # docs comments engine
    - path: github.com/hbstack/docs/modules/giscus
    # - path: github.com/hbstack/docs/modules/utterances
    # - path: github.com/hbstack/docs/modules/disqus

    # docs modules
    - path: github.com/hbstack/docs/modules/content-panel
    - path: github.com/hbstack/docs/modules/toc-scrollspy

    # other modules
    - path: github.com/hugomods/google-analytics
    - path: github.com/hugomods/google-adsense

    # recommended modules
    - path: github.com/hbstack/meta/recommended
```
