### DISCUSSION TITLE
How to disable featured image only inside the post, but show in home page

### DISCUSSION THREAD

**Discussion by evandde** [hbstack/.github#18] [Q&A] [answered]
Sorry for bother you with too many questions...

I found the discussion https://github.com/orgs/hbstack/discussions/4.
But it discusses only about featured image on the home page (front page(?))

I want to make the image show in the home page, but not to show in the post itself.

In the post, the image is enlarged to fit the body width, so that it sometimes looks bad...

Is there any option to remove featured image only in the post?

**Comment by razonyang** [comment]
Yep, that is possible, I will write a guide for removing built-in modules later.

**Comment by razonyang** [comment]
For quick fix, you can set the following parameters.

```yaml
hugopress:
  modules:
    hb-blog-post-featured-image:
      disabled: true
    hb-docs-doc-featured-image:
      disabled: true
```

The `hb-blog-post-featured-image`/`hb-docs-doc-featured-image` for blog/docs layout.
