### DISCUSSION TITLE
Newbie question: can't seem to remove nav element from top of blog-main container on start page

### DISCUSSION THREAD

**Discussion by perweij** [hbstack/.github#23] [Q&A]
Hi! I'm learning the excellent hbstack, and am trying to remove the navigation block above the blog-main part of the landing page. It is shown as a blue, disabled icon link with a counter above. It's possibly the result of some default setting in some module that I need to figure out how to disable explicitly.

```
<nav class="nav nav-fill mb-5">
  <a class="nav-link d-flex flex-column disabled" href="/en/" title="Pages">
    <span class="mb-3 text-body fw-bold">3</span>
    <span class="text-body"><svg aria-hidden="true" class="bi bi-file-richtextbi bi-file-richtext hi-svg-inline text-primary" fill="currentColor" height="2.25em" viewBox="0 0 16 16" width="2.25em" xmlns="http://www.w3.org/2000/svg">
  <path d="..."></path>
</svg></span>
  </a>
</nav>
```

![image](https://github.com/hbstack/.github/assets/13719550/69c2ba65-659c-4a7d-acaf-bdf861f53791)

I am using the modified example site files:

config/_default/hugo.yaml:
```
baseURL: https://test.com
title: Test
copyright: Test
defaultContentLanguage: en
defaultContentLanguageInSubdir: true # disable this to remove the default language code from URL, i.e. /en/docs -> /docs.
enableRobotsTXT: true
timeout: 120s # images processing takes a long time, it's recommended to commit the resources folder for improve the build performance.
enableEmoji: true

permalinks:
  blog: /blog/:year/:month/:title

module:
  imports:
    - path: github.com/hugomods/icons/vendors/font-awesome
    - path: github.com/hbstack/meta/recommended
    

outputs:
  home:
    - HTML
    - Offline        # required by PWA module for displaying the offline pages.
    - RSS
    - SearchIndex    # required by search module.
    - WebAppManifest # required by PWA module to make your site installable.

taxonomies:

build:
  writeStats: true # required by PurgeCSS.

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    lineNos: true
    lineNumbersInTable: false


security:
  funcs:
    getenv:
      - ^HUGO
      - CI$
      - PWD
```

config/_default/params.yaml:
```
description: Test

hb:
  header:
    logo_bg: '#712cf9' # logo background color, used by logo with transparent background.
    
  footer:
    powered_by: false
    
  blog:
    full_width: false # when true, the blog layout takes full width.
    paginate: 12 # paginate.
    post_thumbnail_placeholder: #HB THEME # the text of thumbnail placeholder, default to site title.
    home: # homepage settings.
    giscus:
      repo: hbstack/theme
      repo_id: R_kgDOJP3qtA
      category_id: DIC_kwDOJP3qtM4CVavM

  content_panel:
    bottom: 20px
    repo:
      branch: main
      repo: user/name
      service: github
      subpath: exampleSite

seo:
  favicons: # see https://hugomods.com/en/docs/seo/#favicons-module
    icon: images/logo.png # use logo as favicon.

pwa:
  debug: false

search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false

mermaid:
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hugopress:
  modules:
    hb-custom:
      hooks:
        head-end:
          cacheable: true
        body-end:
          cacheable: true
```

**Comment by razonyang** [comment]
Hi, thanks for using this theme. I remember there is an parameter `hb.blog.home.taxonomies` for controling this, but it's missed from the docs, I'll fix it later.

```yaml
hb:
  blog:
    home:
       taxonomies: false
```
