### DISCUSSION TITLE
announcement-bar error

### DISCUSSION THREAD

**Discussion by evandde** [hbstack/.github#24] [Q&A] [answered]
Hello. Thanks for the development of announcement-bar. It's really interesting.

But when I use it, it occurs an error like

```
ERROR [ko] REF_NOT_FOUND: Ref "modules/enhancement/announcement-bar": "E:\hugo\evanote\content\_index.md:3:2": page not found
```

My `content/_index.md` is like this (very simple)

```
---
title: EvaNOTE
---
```

Even though I change the data/announcements/ko.yaml to data/announcements/en.yaml with [en] mode in language parameters in hugo.yaml, it occurs same error like

```
ERROR [en] REF_NOT_FOUND: Ref "modules/enhancement/announcement-bar": "E:\hugo\evanote\content\_index.md:3:2": page not found
```

---

What I did

1. in hugo.yaml, added
   ```
   module:
     imports:
       path: github.com/hbstack/announcement-bar
   ```

2. in languages.yaml, changed
   ```
   ko:
     languageName: Korean
     weight: 1
   ```

3. in params.yaml, added
   ```
   hb:
     announcement_bar:
        bg: '#dc3545'
        color: '#fff'
        interval: 5000
   ```

4. And then made data/announcements/ko.yaml like
   ```
   announcement-bar:
     title: "\U0001F4E2 Announcement bar was released, [check it out]({{< relref `modules/enhancement/announcement-bar`>}})!"
     weight: 2
   hello:
     title: "\U0001F44F Hi there! Welcome to HB framework!"
     weight: 1
   ```
