### DISCUSSION TITLE
How to customize title to be like these?

### DISCUSSION THREAD

**Discussion by TetraTheta** [hbstack/.github#31] [Q&A] [answered]
I've found that title of the page is too long to me. I want to modify title of the page to be simple like this:

### Site main page
```
<site name> - <site description>
```
(This is same as current)

### Category/Series/Tags page
```
<category|series|tags name> - Category|Series|Tags - <site name>
```
(Same as current)

### Section page
1. If parent section exists (`blog` doesn't count for parent section)
   ```
   <parent section name>/<current section name> - <site name>
   ```
2. If parent section doesn't exist (`blog` doesn't count for parent section)
   ```
   <current section name> - <site name>
   ```

This will only exclude `blog` for title, not `docs`.

I've done similar thing to `partials/hb/modules/blog/post/meta/first-section.html`.
```html
{{- with .CurrentSection -}}
<span class="hb-blog-post-section">
  <div class="badge bg-secondary text-decoration-none fw-normal">
    {{- with .Parent -}}
      {{- if and (not .IsHome) (ne .Title "블로그") -}}
    <a class="bg-secondary text-decoration-none fw-normal" style="color: var(--hb-badge-color);" href="{{ .RelPermalink }}">{{ .Title }}</a>
    <div class="bg-secondary text-decoration-none fw-normal" style="display: inline-block; color: var(--hb-badge-color); opacity: 0.45;">&nbsp;/&nbsp;</div>
      {{- end -}}
    {{- end -}}
    <a class="bg-secondary text-decoration-none fw-normal" style="color: var(--hb-badge-color);" href="{{ .RelPermalink }}">{{ .Title }}</a>
  </div>
</span>
{{- end -}}
```
This will only exclude `blog`('블로그') from parent section. It won't display '블로그' or 'Blog' to section name.

### Post page
```
<post title> - <site name>
```
This will remove all section information from title.

---

My guess is that I should modify lots of files for this...

**Comment by razonyang** [comment, marked as answer]
There is an undocumented parameter called `title_sections` of github.com/hugomods/base module, when false, the section titles will not be included into the titles.


```yaml
params:
  title_sections: false
```

**Reply by TetraTheta** [reply]
It doesn't render 'parent section' like `<parent section name>/<current section name>`, but that's OK with me. 

Thank you for letting me know about it!

**Reply by razonyang** [reply]
I could some parameters to control this, such as `title_sections_depth` which indicates the depth of sections, but I'm not sure how people like which sections to be displayed. 

Takes `Hello World - JS - Programming - Blog - Site` (`/blog/programming/js/hello-world`) as an example, there are three sections `JS` (parent section), `Programming` and `Blog` (root section).

I'm not sure which sections are prefer to be keep when the `title_sections_depth` is set as `1`:

1) `Hello World - Blog - Site`
2)  `Hello World - JS - Site`.

**Reply by TetraTheta** [reply]
I think my use case would be niche use case. There are so many 'preferred title structure' like these:
1. `Hello World - Site`
2. `Hello World - Programming - Site`
3. `Hello World - Programming/JS - Site` (Using `/` instead of `-`)
4. `Hello World - Programming - JS - Site` (Without Blog part)
5. `Hello World - Programming/JS/Blog - Site` (Using `/` instead of `-`, Blog included)
6. `Hello World - Programming - JS - Blog - Site` (Current way)
7. `Hello World - JS/Programming - Site` (Parent section comes first)
8. `Hello World - Blog/JS/Programming - Site` (Parent section comes first, Blog included)

Maybe letting user to decide how title would structured with template just like Hugo does to Date be good idea.
```yaml
params:
  title:
    section:
      order: order: 'default'|'reverse' # 'default' will put root/topmost section first. 'reverse' will do opposite
      depth: 2 # From deepest section to root section
      delim: ' - '|'/' # string to put between section title
      exclude_root_section: true # Exclude 'Blog' or 'Docs' section?
    format: # Use 'post_title', 'section', 'site', 'site_description', 'post_description' etc. for templating
      site: 'site - site_description'
      texanomy: 'texanomy - site'
      section: 'section - site'
      post: 'post_title - section - site'
```
Yes, this will definitely make extra complexity to user and dev...

**Reply by razonyang** [reply]
Yep, it's complex, but I don't whether to have them all, at least the [sections depth and order](https://github.com/hugomods/base/issues/26) is good to have, thanks for your opinions.

**Reply by TetraTheta** [reply]
Thank you for taking this into account!

I will close this discussion for awhile, and try to re-open it after the linked issue is resolved and I still can't get the idea of how to modify it (if needed), if I don't forget that I should re-open this rather than opening new discussion...

**Reply by TetraTheta** [reply]
I finally managed to get title I want. 

First, I created `i18n/ko.toml` and put these line in it.
```toml
# I don't need total page number
[paginator_title]
other = "{{ .PageNumber }} 페이지"
```
And modified `layouts/partials/base/title.html` like this
```html
{{- $titles := slice .Title -}}
{{/* Page Title */}}
{{/* Paginator */}}
{{- with .Paginator -}}
  {{- if gt .PageNumber 1 -}}
    {{- $titles = $titles | append "-" (i18n "paginator_title" .) }}
  {{- end -}}
{{- end -}}
{{/* Section */}}
{{- $sections := (partial "base/functions/sections-titles" .) | collections.Reverse -}}
{{/* remove '블로그' from sections */}}
{{- if eq (index $sections 0) "블로그" -}}
  {{- $sections = after 1 $sections -}}
{{- end -}}
{{- if gt ($sections | len) 1 -}}
  {{- $titles = $titles | append "-" (delimit $sections "/") -}}
{{- end -}}
{{/* Title */}}
{{- if not .IsHome -}}
  {{- $titles = $titles | append "-" .Site.Title -}}
{{- end -}}
{{- delimit $titles " " -}}
```
I hard-coded delimiters because I use different delimiters for sections and I don't have a plan to define them in `params.yaml`.

Thank you for the [updates](https://github.com/hugomods/base/commits/main/layouts/partials/base/title.html). I couldn't figure out how to configure the title without that.

---

As for missing translation in [`i18n/ko.toml`](https://github.com/hugomods/base/tree/main/i18n), here are some translation candidates.
```toml
# Only current page number
# e.g. '3 페이지'
[paginator_title]
other = "{{ .PageNumber }} 페이지"
# Basic translation
# e.g. '5 페이지 중 3 페이지'
[paginator_title]
other = "{{ .TotalPages }} 페이지 중 {{ .PageNumber }} 페이지"
# Basic translation, but simplified (recommended)
# '/' is commonly used separator for current page number and total page number, at least in Korea.
# You can choose '/' or ' / '(spaces around '/') for this. I chose '/' because it takes less space.
# e.g. '3/5 페이지'
[paginator_title]
other = "{{ .PageNumber }}/{{ .TotalPages }} 페이지"
```
I will leave these in here instead of creating PR because I'm not sure which one you'd like.
