### DISCUSSION TITLE
Authors page translation

### DISCUSSION THREAD

**Discussion by gavlinski** [hbstack/.github#35] [General]
Hi, where can we translate "Pages", "Sections" and "Types" strings from [authors page](https://hbstack.dev/authors/)? And what is the meaning of each one?

![image](https://github.com/hbstack/.github/assets/1410375/a96198a7-1e8c-4f45-91fb-52c9d48756d8)

https://hbstack.dev/authors/

Thanks for all your support.

**Comment by razonyang** [comment]
| Term | Desc |
| --- | --- |
| Pages | How many pages wrote by the author |
| Sections | The number of unique sections of pages related to the author |
| Types | The number of unique types of pages related to the author |

I didn't translate those terms, since it's still in experimental, I want to know your opinions about the matric terms before translating them.

**Comment by razonyang** [comment]
Translated, the fallback as follows, `Pages` was retitle as `Posts`.

```toml
[metrics_page_sections]
other = "Sections"

[metrics_page_types]
other = "Types"

[metrics_posts]
other = "Posts"
```
