### DISCUSSION TITLE
settings of the search module

### DISCUSSION THREAD

**Discussion by Gordolin** [hbstack/.github#42] [Show and tell]
The default settings in params.yaml of the seach-module did not work very well for me.
After some try an error i used this settings:

See https://hugomods.com/search/configurations/.

```yaml
// params.yaml
search:
  stall_threshold: 300
  min_match_char_length: 3
  case_sensitive: false
  threshold: 0.0
  index_content: true
  ignore_location: true
```
  
 There are no performance issues for me, my site is generates about 1700 pages, but it runs on a local NAS.
  
 May be it is helpfull for somebody.
