### DISCUSSION TITLE
How can I reset scrollbar style to web browser's default value?

### DISCUSSION THREAD

**Discussion by TetraTheta** [hbstack/.github#45] [Q&A] [answered]
I personally don't like how scrollbar is styled in HB theme. So I want it to be reset to web browser's default value.

But I can't figure out how to disable such thing with `assets/hb/modules/custom/scss/index.scss`.
```scss
:root {
  scrollbar-color: auto !important;
  scrollbar-width: auto !important;
}
::-webkit-scrollbar {
  width: auto !important;
  height: auto !important;
}
::-webkit-scrollbar-corner, ::-webkit-scrollbar-thumb, ::-webkit-scrollbar-track {
  background: auto !important;
}
```
None of these works. `auto`, `initial`, `reset`, `unset` also don't work.

How can I reset scrollbar to web browser's default value?

---

PS.

According to [this answer](https://superuser.com/a/417750), `::-webkit-scrollbar` cannot be 'reset' once overridden. If then, I'll have to copy original source to my local installation, and remove such lines... :(
