### DISCUSSION TITLE
How to configure Discus?

### DISCUSSION THREAD

**Discussion by FuadEfendi** [hbstack/.github#5] [Q&A] [answered]
Hi Razon,

How to configure Giscus, for example, how to configure `og:title`?

This is what I found in initial example:
```yml
   giscus:
       repo: hbstack/theme
         repo_id: R_kgDOJP3qtA
         category_id: DIC_kwDOJP3qtM4CVavM
```

And where can I find repo Id?
https://giscus.app/

Thanks,
