### DISCUSSION TITLE
Divider for header menu

### DISCUSSION THREAD

**Discussion by TetraTheta** [hbstack/.github#72] [Ideas]
I wish if I can put some kind of 'divider' or 'separator' to header menu like this:

![E1](https://github.com/user-attachments/assets/25fc1821-e224-43e5-aa62-b48fccbaedbb)

![E2](https://github.com/user-attachments/assets/844c3bdb-a4ae-416d-aec2-d916a751cadf)

The style of the divider(separator) wouldn't matter if it clearly tells people that it is divider(separator). As you can see, my *example* isn't good example, because my example *collides* with sidebar element divider.

I'm not good at design stuff. 😞

Using `_separator` or `_divider` as defining divider(separator) would be like this:

```yaml
# menus.yml
main:
  - name: First Menu
  - name: Second Menu
  - name: _separator # or _divider
  - name: Separated First Menu
  - name: Separated Second Menu
```

I think no one will use `_separator` or `_divider` as valid menu item name, so these will be unique name for divider(separator).

**Comment by razonyang** [comment]
It's a good feature to have, but we need a proper/good way to configure it.

## Divider as menu items

Treat the divider as a menu item, similar to the example you posted above, but the drawback is that you have to specify `identifier` or `name` for each dividers when there are multiple dividers, otherwise there will be only one divider left.

```yaml
main:
  - name: A
  - identifier: divider-1
    params:
      divider: true # required, indicate whether this item is a divider.
  - name: B
```

## New menu item parameters

```yaml
main:
  -  name: A
     params:
       divider: true
  -  name: B
```

Result as `A | B`, however it seems weird, since the divider belongs to both of those neighbouring menu items (A and B in this case), not just one of them.

So in my opinon, I prefer the first implementation.
