### DISCUSSION TITLE
Taxonomies with custom Colors in meta

### DISCUSSION THREAD

**Discussion by Gordolin** [hbstack/.github#77] [Q&A] [answered]
Is it possible to use custom colors for the taxonomy badges in the blog list and post views (wich is now shown in grey)?

I would like to create a new taxonomy called rating, to set ratings like stars for list of books and movies. 
I'm currently doing this with the custom hook "hb-blog-post-meta" and a frontmatter page param. But I would like to do this with a taxonomy to show, for example, all posts with a rating of 3.

Part of my hb-blog-post-meta.html
```
<span class="badge bg-primary text-decoration-none fw-normal mt-2" style="font-size: 0.825rem;" >
        Rating: {{ .Page.Params.rating }} {{ partial "icons/icon" $ctx }} 
        </span>
```

Is it possible to use icons for the taxonomies or replace the "#" in tags with another sign?

**Comment by razonyang** [comment, marked as answer]
There is no such parameter for this purpose, you can achieve this via CSS.

> Is it possible to use custom colors for the taxonomy badges in the blog list and post views

```scss
.hb-blog-post-taxonomy {
    background-color: red !important;
}
```

> Is it possible to use icons for the taxonomies or replace the "#" in tags with another sign?

```scss
.hb-blog-post-taxonomy {
    &:before {
        content: "⭐";
    }
}
```
