### DISCUSSION TITLE
How to get toc heading level to depth four and more

### DISCUSSION THREAD

**Discussion by AbdulSayyed** [hbstack/.github#91] [Q&A] [answered]
In my blog posts or docs, on the right side appears `on this page` where markdown headings are converted into toc. I am not able to see heading four. How to make it appear in toc. Thanks

**Comment by razonyang** [comment, marked as answer]
Hi, the default ToC levels is `2-3`, you can tweak the `markup.tableOfContents` config to suit your needs.

```yaml
// hugo.yaml
markup:
  tableOfContents:
    endLevel: 6
    ordered: false
    startLevel: 2
```
