### DISCUSSION TITLE
theme-cards SCSS

### DISCUSSION THREAD

**Discussion by if-itchief** [hbstack/.github#95] [Q&A]
Dear

I hope this message finds you well.

I’ve been trying to set up and use your theme, theme-cards, with Hugo, but I keep encountering multiple errors during the installation and setup process. Despite following the available documentation, I’ve run into issues such as SCSS transformation errors, undefined mixins, and difficulties with module configuration.

Unfortunately, as someone relatively new to this, the troubleshooting process has been quite challenging. Would it be possible for you to provide a more detailed step-by-step guide or a video tutorial tailored for beginners? It would be incredibly helpful in understanding how to properly install and configure the theme and resolve the common issues.

Thank you in advance for your support, and I greatly appreciate your work on this project. Please let me know if there’s anything specific I should check in the meantime.

Best regards,

**Comment by if-itchief** [comment]
ERROR TOCSS-DART: failed to transform "hb/scss/index.scss" (text/x-scss): got unexpected EOF when executing "sass". The user running hugo must have read and execute permissions on this program. With execute permissions only, this error is thrown.
Built in 1166 ms

Error: error building site: TOCSS-DART: failed to transform "hb/scss/index.scss" (text/x-scss): got unexpected EOF when executing "sass". The user running hugo must have read and execute permissions on this program. With execute permissions only, this error is thrown.

**Comment by razonyang** [comment]
Does this help?

https://discourse.gohugo.io/t/tocss-dart-failed-to-transform-scss-main-scss-execute-permissions/43267

**Comment by razonyang** [comment]
I got tired yesterday and just woke up. Do you have any updates?

If the issue is still unresolved.

## 1. Try Docker to avoid most environmental issues.

Create file `docker-compose.yaml` with the following content, and then start service via `docker compose up`.

```yaml
name: mysite

services:
  server:
    image: hugomods/hugo:exts-non-root
    command: server -D
    volumes:
      - ./:/src
      - ~/.cache/hugo_cache:/tmp/hugo_cache
    ports:
      - 1313:1313
    env_file:
      - path: .env
        required: false
```

## 2. Provide more details to reproduce.

1. A repo with the code.
2. The operating system.
3. How do you install Sass and Hugo?
