### DISCUSSION TITLE
Error artifact v3

### DISCUSSION THREAD

**Discussion by sandsoncosta** [hbstack/.github#99] [Q&A] [answered]
Hi Razon!
Can you help this?

I uploaded an update and github pages gave me an error:
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

What did I do?
I redownload KaTeX.

Since I don't know how to re-commit, I changed the text and sent it:
git push origin main

And continue:
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

![image](https://github.com/user-attachments/assets/fddbb346-e56e-46f4-8bcf-f7ee651d32cd)

**Comment by sandsoncosta** [comment, marked as answer]
I got it!

Updated:

```
      - name: Upload artifact
        # uses: actions/upload-pages-artifact@v1
        uses: actions/upload-artifact@v4
        with:
          path: ./public
```
